/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.5.57-0ubuntu0.14.04.1 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `country` (
	`country_code` varchar (6),
	`country_name` varchar (150)
); 
insert into `country` (`country_code`, `country_name`) values('AF','Afghanistan');
insert into `country` (`country_code`, `country_name`) values('AL','Albania');
insert into `country` (`country_code`, `country_name`) values('DZ','Algeria');
insert into `country` (`country_code`, `country_name`) values('DS','American Samoa');
insert into `country` (`country_code`, `country_name`) values('AD','Andorra');
insert into `country` (`country_code`, `country_name`) values('AO','Angola');
insert into `country` (`country_code`, `country_name`) values('AI','Anguilla');
insert into `country` (`country_code`, `country_name`) values('AQ','Antarctica');
insert into `country` (`country_code`, `country_name`) values('AG','Antigua and Barbuda');
insert into `country` (`country_code`, `country_name`) values('AR','Argentina');
insert into `country` (`country_code`, `country_name`) values('AM','Armenia');
insert into `country` (`country_code`, `country_name`) values('AW','Aruba');
insert into `country` (`country_code`, `country_name`) values('AU','Australia');
insert into `country` (`country_code`, `country_name`) values('AT','Austria');
insert into `country` (`country_code`, `country_name`) values('AZ','Azerbaijan');
insert into `country` (`country_code`, `country_name`) values('BS','Bahamas');
insert into `country` (`country_code`, `country_name`) values('BH','Bahrain');
insert into `country` (`country_code`, `country_name`) values('BD','Bangladesh');
insert into `country` (`country_code`, `country_name`) values('BB','Barbados');
insert into `country` (`country_code`, `country_name`) values('BY','Belarus');
insert into `country` (`country_code`, `country_name`) values('BE','Belgium');
insert into `country` (`country_code`, `country_name`) values('BZ','Belize');
insert into `country` (`country_code`, `country_name`) values('BJ','Benin');
insert into `country` (`country_code`, `country_name`) values('BM','Bermuda');
insert into `country` (`country_code`, `country_name`) values('BT','Bhutan');
insert into `country` (`country_code`, `country_name`) values('BO','Bolivia');
insert into `country` (`country_code`, `country_name`) values('BA','Bosnia and Herzegovina');
insert into `country` (`country_code`, `country_name`) values('BW','Botswana');
insert into `country` (`country_code`, `country_name`) values('BV','Bouvet Island');
insert into `country` (`country_code`, `country_name`) values('BR','Brazil');
insert into `country` (`country_code`, `country_name`) values('IO','British Indian Ocean Territory');
insert into `country` (`country_code`, `country_name`) values('BN','Brunei Darussalam');
insert into `country` (`country_code`, `country_name`) values('BG','Bulgaria');
insert into `country` (`country_code`, `country_name`) values('BF','Burkina Faso');
insert into `country` (`country_code`, `country_name`) values('BI','Burundi');
insert into `country` (`country_code`, `country_name`) values('KH','Cambodia');
insert into `country` (`country_code`, `country_name`) values('CM','Cameroon');
insert into `country` (`country_code`, `country_name`) values('CA','Canada');
insert into `country` (`country_code`, `country_name`) values('CV','Cape Verde');
insert into `country` (`country_code`, `country_name`) values('KY','Cayman Islands');
insert into `country` (`country_code`, `country_name`) values('CF','Central African Republic');
insert into `country` (`country_code`, `country_name`) values('TD','Chad');
insert into `country` (`country_code`, `country_name`) values('CL','Chile');
insert into `country` (`country_code`, `country_name`) values('CN','China');
insert into `country` (`country_code`, `country_name`) values('CX','Christmas Island');
insert into `country` (`country_code`, `country_name`) values('CC','Cocos (Keeling) Islands');
insert into `country` (`country_code`, `country_name`) values('CO','Colombia');
insert into `country` (`country_code`, `country_name`) values('KM','Comoros');
insert into `country` (`country_code`, `country_name`) values('CG','Congo');
insert into `country` (`country_code`, `country_name`) values('CK','Cook Islands');
insert into `country` (`country_code`, `country_name`) values('CR','Costa Rica');
insert into `country` (`country_code`, `country_name`) values('HR','Croatia (Hrvatska)');
insert into `country` (`country_code`, `country_name`) values('CU','Cuba');
insert into `country` (`country_code`, `country_name`) values('CY','Cyprus');
insert into `country` (`country_code`, `country_name`) values('CZ','Czech Republic');
insert into `country` (`country_code`, `country_name`) values('DK','Denmark');
insert into `country` (`country_code`, `country_name`) values('DJ','Djibouti');
insert into `country` (`country_code`, `country_name`) values('DM','Dominica');
insert into `country` (`country_code`, `country_name`) values('DO','Dominican Republic');
insert into `country` (`country_code`, `country_name`) values('TP','East Timor');
insert into `country` (`country_code`, `country_name`) values('EC','Ecuador');
insert into `country` (`country_code`, `country_name`) values('EG','Egypt');
insert into `country` (`country_code`, `country_name`) values('SV','El Salvador');
insert into `country` (`country_code`, `country_name`) values('GQ','Equatorial Guinea');
insert into `country` (`country_code`, `country_name`) values('ER','Eritrea');
insert into `country` (`country_code`, `country_name`) values('EE','Estonia');
insert into `country` (`country_code`, `country_name`) values('ET','Ethiopia');
insert into `country` (`country_code`, `country_name`) values('FK','Falkland Islands (Malvinas)');
insert into `country` (`country_code`, `country_name`) values('FO','Faroe Islands');
insert into `country` (`country_code`, `country_name`) values('FJ','Fiji');
insert into `country` (`country_code`, `country_name`) values('FI','Finland');
insert into `country` (`country_code`, `country_name`) values('FR','France');
insert into `country` (`country_code`, `country_name`) values('FX','France, Metropolitan');
insert into `country` (`country_code`, `country_name`) values('GF','French Guiana');
insert into `country` (`country_code`, `country_name`) values('PF','French Polynesia');
insert into `country` (`country_code`, `country_name`) values('TF','French Southern Territories');
insert into `country` (`country_code`, `country_name`) values('GA','Gabon');
insert into `country` (`country_code`, `country_name`) values('GM','Gambia');
insert into `country` (`country_code`, `country_name`) values('GE','Georgia');
insert into `country` (`country_code`, `country_name`) values('DE','Germany');
insert into `country` (`country_code`, `country_name`) values('GH','Ghana');
insert into `country` (`country_code`, `country_name`) values('GI','Gibraltar');
insert into `country` (`country_code`, `country_name`) values('GK','Guernsey');
insert into `country` (`country_code`, `country_name`) values('GR','Greece');
insert into `country` (`country_code`, `country_name`) values('GL','Greenland');
insert into `country` (`country_code`, `country_name`) values('GD','Grenada');
insert into `country` (`country_code`, `country_name`) values('GP','Guadeloupe');
insert into `country` (`country_code`, `country_name`) values('GU','Guam');
insert into `country` (`country_code`, `country_name`) values('GT','Guatemala');
insert into `country` (`country_code`, `country_name`) values('GN','Guinea');
insert into `country` (`country_code`, `country_name`) values('GW','Guinea-Bissau');
insert into `country` (`country_code`, `country_name`) values('GY','Guyana');
insert into `country` (`country_code`, `country_name`) values('HT','Haiti');
insert into `country` (`country_code`, `country_name`) values('HM','Heard and Mc Donald Islands');
insert into `country` (`country_code`, `country_name`) values('HN','Honduras');
insert into `country` (`country_code`, `country_name`) values('HK','Hong Kong');
insert into `country` (`country_code`, `country_name`) values('HU','Hungary');
insert into `country` (`country_code`, `country_name`) values('IS','Iceland');
insert into `country` (`country_code`, `country_name`) values('IN','India');
insert into `country` (`country_code`, `country_name`) values('IM','Isle of Man');
insert into `country` (`country_code`, `country_name`) values('ID','Indonesia');
insert into `country` (`country_code`, `country_name`) values('IR','Iran (Islamic Republic of)');
insert into `country` (`country_code`, `country_name`) values('IQ','Iraq');
insert into `country` (`country_code`, `country_name`) values('IE','Ireland');
insert into `country` (`country_code`, `country_name`) values('IL','Israel');
insert into `country` (`country_code`, `country_name`) values('IT','Italy');
insert into `country` (`country_code`, `country_name`) values('CI','Ivory Coast');
insert into `country` (`country_code`, `country_name`) values('JE','Jersey');
insert into `country` (`country_code`, `country_name`) values('JM','Jamaica');
insert into `country` (`country_code`, `country_name`) values('JP','Japan');
insert into `country` (`country_code`, `country_name`) values('JO','Jordan');
insert into `country` (`country_code`, `country_name`) values('KZ','Kazakhstan');
insert into `country` (`country_code`, `country_name`) values('KE','Kenya');
insert into `country` (`country_code`, `country_name`) values('KI','Kiribati');
insert into `country` (`country_code`, `country_name`) values('KP','Korea, Democratic People\'s Republic of');
insert into `country` (`country_code`, `country_name`) values('KR','Korea, Republic of');
insert into `country` (`country_code`, `country_name`) values('XK','Kosovo');
insert into `country` (`country_code`, `country_name`) values('KW','Kuwait');
insert into `country` (`country_code`, `country_name`) values('KG','Kyrgyzstan');
insert into `country` (`country_code`, `country_name`) values('LA','Lao People\'s Democratic Republic');
insert into `country` (`country_code`, `country_name`) values('LV','Latvia');
insert into `country` (`country_code`, `country_name`) values('LB','Lebanon');
insert into `country` (`country_code`, `country_name`) values('LS','Lesotho');
insert into `country` (`country_code`, `country_name`) values('LR','Liberia');
insert into `country` (`country_code`, `country_name`) values('LY','Libyan Arab Jamahiriya');
insert into `country` (`country_code`, `country_name`) values('LI','Liechtenstein');
insert into `country` (`country_code`, `country_name`) values('LT','Lithuania');
insert into `country` (`country_code`, `country_name`) values('LU','Luxembourg');
insert into `country` (`country_code`, `country_name`) values('MO','Macau');
insert into `country` (`country_code`, `country_name`) values('MK','Macedonia');
insert into `country` (`country_code`, `country_name`) values('MG','Madagascar');
insert into `country` (`country_code`, `country_name`) values('MW','Malawi');
insert into `country` (`country_code`, `country_name`) values('MY','Malaysia');
insert into `country` (`country_code`, `country_name`) values('MV','Maldives');
insert into `country` (`country_code`, `country_name`) values('ML','Mali');
insert into `country` (`country_code`, `country_name`) values('MT','Malta');
insert into `country` (`country_code`, `country_name`) values('MH','Marshall Islands');
insert into `country` (`country_code`, `country_name`) values('MQ','Martinique');
insert into `country` (`country_code`, `country_name`) values('MR','Mauritania');
insert into `country` (`country_code`, `country_name`) values('MU','Mauritius');
insert into `country` (`country_code`, `country_name`) values('TY','Mayotte');
insert into `country` (`country_code`, `country_name`) values('MX','Mexico');
insert into `country` (`country_code`, `country_name`) values('FM','Micronesia, Federated States of');
insert into `country` (`country_code`, `country_name`) values('MD','Moldova, Republic of');
insert into `country` (`country_code`, `country_name`) values('MC','Monaco');
insert into `country` (`country_code`, `country_name`) values('MN','Mongolia');
insert into `country` (`country_code`, `country_name`) values('ME','Montenegro');
insert into `country` (`country_code`, `country_name`) values('MS','Montserrat');
insert into `country` (`country_code`, `country_name`) values('MA','Morocco');
insert into `country` (`country_code`, `country_name`) values('MZ','Mozambique');
insert into `country` (`country_code`, `country_name`) values('MM','Myanmar');
insert into `country` (`country_code`, `country_name`) values('NA','Namibia');
insert into `country` (`country_code`, `country_name`) values('NR','Nauru');
insert into `country` (`country_code`, `country_name`) values('NP','Nepal');
insert into `country` (`country_code`, `country_name`) values('NL','Netherlands');
insert into `country` (`country_code`, `country_name`) values('AN','Netherlands Antilles');
insert into `country` (`country_code`, `country_name`) values('NC','New Caledonia');
insert into `country` (`country_code`, `country_name`) values('NZ','New Zealand');
insert into `country` (`country_code`, `country_name`) values('NI','Nicaragua');
insert into `country` (`country_code`, `country_name`) values('NE','Niger');
insert into `country` (`country_code`, `country_name`) values('NG','Nigeria');
insert into `country` (`country_code`, `country_name`) values('NU','Niue');
insert into `country` (`country_code`, `country_name`) values('NF','Norfolk Island');
insert into `country` (`country_code`, `country_name`) values('MP','Northern Mariana Islands');
insert into `country` (`country_code`, `country_name`) values('NO','Norway');
insert into `country` (`country_code`, `country_name`) values('OM','Oman');
insert into `country` (`country_code`, `country_name`) values('PK','Pakistan');
insert into `country` (`country_code`, `country_name`) values('PW','Palau');
insert into `country` (`country_code`, `country_name`) values('PS','Palestine');
insert into `country` (`country_code`, `country_name`) values('PA','Panama');
insert into `country` (`country_code`, `country_name`) values('PG','Papua New Guinea');
insert into `country` (`country_code`, `country_name`) values('PY','Paraguay');
insert into `country` (`country_code`, `country_name`) values('PE','Peru');
insert into `country` (`country_code`, `country_name`) values('PH','Philippines');
insert into `country` (`country_code`, `country_name`) values('PN','Pitcairn');
insert into `country` (`country_code`, `country_name`) values('PL','Poland');
insert into `country` (`country_code`, `country_name`) values('PT','Portugal');
insert into `country` (`country_code`, `country_name`) values('PR','Puerto Rico');
insert into `country` (`country_code`, `country_name`) values('QA','Qatar');
insert into `country` (`country_code`, `country_name`) values('RE','Reunion');
insert into `country` (`country_code`, `country_name`) values('RO','Romania');
insert into `country` (`country_code`, `country_name`) values('RU','Russian Federation');
insert into `country` (`country_code`, `country_name`) values('RW','Rwanda');
insert into `country` (`country_code`, `country_name`) values('KN','Saint Kitts and Nevis');
insert into `country` (`country_code`, `country_name`) values('LC','Saint Lucia');
insert into `country` (`country_code`, `country_name`) values('VC','Saint Vincent and the Grenadines');
insert into `country` (`country_code`, `country_name`) values('WS','Samoa');
insert into `country` (`country_code`, `country_name`) values('SM','San Marino');
insert into `country` (`country_code`, `country_name`) values('ST','Sao Tome and Principe');
insert into `country` (`country_code`, `country_name`) values('SA','Saudi Arabia');
insert into `country` (`country_code`, `country_name`) values('SN','Senegal');
insert into `country` (`country_code`, `country_name`) values('RS','Serbia');
insert into `country` (`country_code`, `country_name`) values('SC','Seychelles');
insert into `country` (`country_code`, `country_name`) values('SL','Sierra Leone');
insert into `country` (`country_code`, `country_name`) values('SG','Singapore');
insert into `country` (`country_code`, `country_name`) values('SK','Slovakia');
insert into `country` (`country_code`, `country_name`) values('SI','Slovenia');
insert into `country` (`country_code`, `country_name`) values('SB','Solomon Islands');
insert into `country` (`country_code`, `country_name`) values('SO','Somalia');
insert into `country` (`country_code`, `country_name`) values('ZA','South Africa');
insert into `country` (`country_code`, `country_name`) values('GS','South Georgia South Sandwich Islands');
insert into `country` (`country_code`, `country_name`) values('ES','Spain');
insert into `country` (`country_code`, `country_name`) values('LK','Sri Lanka');
insert into `country` (`country_code`, `country_name`) values('SH','St. Helena');
insert into `country` (`country_code`, `country_name`) values('PM','St. Pierre and Miquelon');
insert into `country` (`country_code`, `country_name`) values('SD','Sudan');
insert into `country` (`country_code`, `country_name`) values('SR','Suriname');
insert into `country` (`country_code`, `country_name`) values('SJ','Svalbard and Jan Mayen Islands');
insert into `country` (`country_code`, `country_name`) values('SZ','Swaziland');
insert into `country` (`country_code`, `country_name`) values('SE','Sweden');
insert into `country` (`country_code`, `country_name`) values('CH','Switzerland');
insert into `country` (`country_code`, `country_name`) values('SY','Syrian Arab Republic');
insert into `country` (`country_code`, `country_name`) values('TW','Taiwan');
insert into `country` (`country_code`, `country_name`) values('TJ','Tajikistan');
insert into `country` (`country_code`, `country_name`) values('TZ','Tanzania, United Republic of');
insert into `country` (`country_code`, `country_name`) values('TH','Thailand');
insert into `country` (`country_code`, `country_name`) values('TG','Togo');
insert into `country` (`country_code`, `country_name`) values('TK','Tokelau');
insert into `country` (`country_code`, `country_name`) values('TO','Tonga');
insert into `country` (`country_code`, `country_name`) values('TT','Trinidad and Tobago');
insert into `country` (`country_code`, `country_name`) values('TN','Tunisia');
insert into `country` (`country_code`, `country_name`) values('TR','Turkey');
insert into `country` (`country_code`, `country_name`) values('TM','Turkmenistan');
insert into `country` (`country_code`, `country_name`) values('TC','Turks and Caicos Islands');
insert into `country` (`country_code`, `country_name`) values('TV','Tuvalu');
insert into `country` (`country_code`, `country_name`) values('UG','Uganda');
insert into `country` (`country_code`, `country_name`) values('UA','Ukraine');
insert into `country` (`country_code`, `country_name`) values('AE','United Arab Emirates');
insert into `country` (`country_code`, `country_name`) values('GB','United Kingdom');
insert into `country` (`country_code`, `country_name`) values('US','United States');
insert into `country` (`country_code`, `country_name`) values('UM','United States minor outlying islands');
insert into `country` (`country_code`, `country_name`) values('UY','Uruguay');
insert into `country` (`country_code`, `country_name`) values('UZ','Uzbekistan');
insert into `country` (`country_code`, `country_name`) values('VU','Vanuatu');
insert into `country` (`country_code`, `country_name`) values('VA','Vatican City State');
insert into `country` (`country_code`, `country_name`) values('VE','Venezuela');
insert into `country` (`country_code`, `country_name`) values('VN','Vietnam');
insert into `country` (`country_code`, `country_name`) values('VG','Virgin Islands (British)');
insert into `country` (`country_code`, `country_name`) values('VI','Virgin Islands (U.S.)');
insert into `country` (`country_code`, `country_name`) values('WF','Wallis and Futuna Islands');
insert into `country` (`country_code`, `country_name`) values('EH','Western Sahara');
insert into `country` (`country_code`, `country_name`) values('YE','Yemen');
insert into `country` (`country_code`, `country_name`) values('ZR','Zaire');
insert into `country` (`country_code`, `country_name`) values('ZM','Zambia');
insert into `country` (`country_code`, `country_name`) values('ZW','Zimbabwe');
